// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQXdyKNITrJCAvJwf1c0Z3ex308OILWWQ',
    appId: '1:300451659202:web:3fdf9a9648ca69cce22a5b',
    messagingSenderId: '300451659202',
    projectId: 'wirdak-5656',
    authDomain: 'wirdak-5656.firebaseapp.com',
    storageBucket: 'wirdak-5656.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyaKYPFzW68molI1zA6CTBNDye5gEDGO0',
    appId: '1:300451659202:android:79ca3b6cb06215b2e22a5b',
    messagingSenderId: '300451659202',
    projectId: 'wirdak-5656',
    storageBucket: 'wirdak-5656.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNQjG5xmhB-W3ZhJyQIIXZIwqB3y9WB1I',
    appId: '1:300451659202:ios:449021c3aa24239de22a5b',
    messagingSenderId: '300451659202',
    projectId: 'wirdak-5656',
    storageBucket: 'wirdak-5656.appspot.com',
    iosBundleId: 'com.example.wirdak',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDNQjG5xmhB-W3ZhJyQIIXZIwqB3y9WB1I',
    appId: '1:300451659202:ios:449021c3aa24239de22a5b',
    messagingSenderId: '300451659202',
    projectId: 'wirdak-5656',
    storageBucket: 'wirdak-5656.appspot.com',
    iosBundleId: 'com.example.wirdak',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCQXdyKNITrJCAvJwf1c0Z3ex308OILWWQ',
    appId: '1:300451659202:web:07e8606ab120e416e22a5b',
    messagingSenderId: '300451659202',
    projectId: 'wirdak-5656',
    authDomain: 'wirdak-5656.firebaseapp.com',
    storageBucket: 'wirdak-5656.appspot.com',
  );
}
